name: concurrency
on:
  push:
    branches:
    - main
concurrency:
  group: one
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run:
          echo "$name"
        env:
          name: ${{ toJSON(github) }}
      - name:
        run: |
          exit 1