name: Parallel-Workflow
on:
  push:
    branches:
      - main
jobs:
  parallel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scan: [sonarqube, checkmarx]
    steps:
      - name: Step-1
        run: echo "This is step-1"

      - name: parallel-1
        if: matrix.scan == 'sonarqube'
        run: |
          sleep 40

      - name:
        if: matrix.scan == 'checkmarx'
        run: |
            sleep 40
